# adding test to make sure that that all our customer id is
# unique and not null

version 2:

models:
    - name: dim_customer
      description: "Dimension table for customers"
      columns:
        - name: customer_id
          description: "Unique identifier for each customer"
          tests:
            - unique
            - not_null